var B3=".GAWYFFUBPI{border:1px solid;padding:3px;width:300px;}.GAWYFFUBAJ{width:100px;height:150px;}.GAWYFFUBOI{color:blue;text-decoration:underline;}.GAWYFFUBBJ{font-size:18pt;}",C3="CellList Example",D3="GAWYFFUBBJ",E3="KeyboardPagingPolicy cannot be null";function F3(a){sQ.call(this,a,(!G3&&(G3=new H3),G3),null)}w(430,403,Sw,F3);var G3=null;function I3(){I3=x;J3=$moduleBase+gz}function H3(){I3()}w(447,1,{},H3);_.ye=function(){return K3(),L3};var J3,M3=null,L3=null;function N3(){}w(448,1,{},N3);
_.ze=function(){return"GAWYFFUBAB"};_.Ae=function(){return"GAWYFFUBBB"};_.Be=function(){return"GAWYFFUBCB"};_.Ce=function(){return"GAWYFFUBDB"};_.De=function(){return"GAWYFFUBEB"};_.yb=function(){return!this.a?(this.a=!0,xI(".GAWYFFUBAB,.GAWYFFUBCB{cursor:pointer;zoom:1;}.GAWYFFUBBB{background:#ffc;}.GAWYFFUBDB{height:"+(O3(),(I3(),M3).a)+zG+M3.d.a+Hx+M3.b+wG+M3.c+"px  repeat-x;background-color:#628cd5;color:white;height:auto;overflow:visible;}"),!0):!1};_.a=!1;
function O3(){O3=x;I3();M3=new yq((Nq(),new Mq((N(),J3))),0,82,26)}function K3(){K3=x;I3();L3=new N3}function P3(){var a=new Wh;PW.call(this);this.a=new jX(this,a)}w(761,755,{},P3);function Q3(a,b){var c;a.i=a.i<a.f.wf()?a.i:a.f.wf();c=a.f.mf(b);a.g=a.f.wf();a.j=!0;gX(a);return c}w(762,1,kh);_.mf=function(a){return Q3(this,a)};w(766,1,qh);_.Nb=function(a){zi(this.c,a)};_.d=!1;_.e=!1;function R3(a){BQ(a);return new S3(zO(a.a))}
function T3(){var a=new In,b=new In;this.c=new wi(this);this.a=a;this.b=b}w(765,766,qh,T3);_.a=null;_.b=null;w(782,1,Mg);_.fc=function(){!this.a.c&&(this.a.c=new U3);Xt(this.a,this.a.c)};
function U3(){var a;this.c=new F3(new wX);a=new V3(this);var b,c,d,e,f,h;b=new bt((L(),em));eV(b,(c=new kt,Ns(c.a,C3,!1),YI(c,g+(W3(),D3)+g),c),30);c=(d=new jt,it(d,(h=new AR,a.a.b=h,h)),d);b.Ye(c,(Ss(),ft),20,null);b.Ye((e=new IU,Ri(e,(f=new jt,it(f,a.a.c),it(f,new hR(12)),f)),e),(Ss(),Ys),0,null);xr(this,b);this.cb.style[q]=lb;this.cb.style[We]=lb;RN(this.c,6);a=new T3;RQ(this.c.V,a);vi(a.c,(!SQ&&(SQ=new di),SQ),new X3(a));qR(this.b,this.c);this.c.r=new Y3;this.a=new P3;KW(this.a,this.c);a=this.a.a;
b=this.a;d=(Xj(),Yj);d.a=ek(d.a,[new Z3(a,b),!0]);$j(d);oO(this.c.V,a.f.wf(),!0);a=this.c;b=(KO(),VQ);NQ(a.V,b);b=this.c;a=(uP(),vP);b=b.V;if(!a)throw new tn(E3);b.d=a}w(811,404,hh,U3);_.a=null;_.b=null;_.c=null;function Y3(){}w(812,1,{},Y3);_.Bb=function(a){lS("Handling update on photo: "+z(a,108).g)};function X3(a){this.a=a}w(813,1,Tw,X3);_.Fe=function(){5<R3(this.a).a.d&&(lS("Cannot select more than 5 items"),JQ(this.a,z(rv(pv(Su(R3(this.a).a))),108),!1))};_.a=null;
function W3(){var a;a=($3(),a4);b4(a)}function V3(a){this.a=a;W3()}w(814,1,{},V3);_.a=null;w(815,1,{},function(){});var a4=null;function b4(a){return!a.a?(a.a=!0,ym(),pj(B3),Dm(),!0):!1}function c4(){}w(816,1,{},c4);_.yb=function(){return b4(this)};_.a=!1;function $3(){$3=x;a4=new c4}function Z3(a,b){this.c=a;this.b=b}w(874,1,{},Z3);_.gc=function(){Q3(this.c,FX(40));fX(this.b);this.a+=40;return 2E3>this.a};_.a=0;_.b=null;_.c=null;function S3(a){this.a=new DX(a.b.a.d);TY(this,a)}w(1E3,970,Og,S3);
W("com.manning.gwtia.ch10.client.celllist.","CellListExamples",811);W("com.manning.gwtia.ch10.client.celllist.","CellListExamples$1",812);W("com.manning.gwtia.ch10.client.celllist.","CellListExamples$2",813);W("com.manning.gwtia.ch10.client.celllist.","CellListExamples_CellTypesUiBinderImpl$Widgets",814);W("com.google.gwt.view.client.","SelectionModel$AbstractSelectionModel",766);W("com.google.gwt.view.client.","MultiSelectionModel",765);
W("com.manning.gwtia.ch10.client.cellwidget.common.","PsuedoDataSource$1",874);W("com.google.gwt.user.cellview.client.","CellList_Resources_default_StaticClientBundleGenerator",447);W("com.google.gwt.user.cellview.client.","CellList_Resources_default_StaticClientBundleGenerator$1",448);W("com.manning.gwtia.ch10.client.celllist.","CellListExamples_CellTypesUiBinderImpl_GenBundle_default_StaticClientBundleGenerator",815);
W("com.manning.gwtia.ch10.client.celllist.","CellListExamples_CellTypesUiBinderImpl_GenBundle_default_StaticClientBundleGenerator$1",816);gi(Qw)(2);